import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Dummy Term acceptability test"
    dialect "mvel"
    when
        d : Description(acceptabilityMap.size() == 1)
    then
        InvalidContent invalid = new InvalidContent(d, "Term should have acceptability entries in one dialect.");
        invalid.ignorePublishedCheck();
        invalidContent.add(invalid);
end
