
import org.ihtsdo.validation.domain.Concept
import org.ihtsdo.validation.domain.Description
import org.ihtsdo.validation.InvalidContent

global java.util.List invalidContent

rule "Double spaces"
    dialect "mvel"
    when
        c : Concept()
        d : Description(conceptId == c.id, term matches ".*  .*")
    then
        invalidContent.add(new InvalidContent(c, "Term should not contain double spaces.", d));
end
